[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# RPC URLs for different networks
[rpc_endpoints]
# Ethereum
ethereum_sepolia = "https://ethereum-sepolia.rpc.subquery.network/public"

# Base
base_sepolia = "https://sepolia.base.org"

# Arbitrum
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

# Optimism
optimism_sepolia = "https://sepolia.optimism.io"

# Polygon
polygon_amoy = "https://rpc-amoy.polygon.technology"

# Avalanche
avalanche_fuji = "https://api.avax-test.network/ext/bc/C/rpc"

# Binance Smart Chain
bsc_testnet = "https://data-seed-prebsc-1-s1.bnbchain.org:8545"

# Blast
blast_sepolia = "https://sepolia.blast.io"

# Berachain
berachain_artio = "https://artio.rpc.berachain.com"

# Ink
ink_sepolia = "https://rpc-gel-sepolia.inkonchain.com"

# Linea
linea_sepolia = "https://rpc.sepolia.linea.build"

# Mode
mode_sepolia = "https://sepolia.mode.network"

# Scroll
scroll_sepolia = "https://sepolia-rpc.scroll.io"

# Soneium
soneium_minato = "https://rpc.minato.soneium.org"

# Sonic
sonic_testnet = "https://rpc.testnet.soniclabs.com"

# Unichain
unichain_sepolia = "https://sepolia.unichain.org"

# zkSync Era
zksync_sepolia = "https://sepolia.era.zksync.dev"

# Etherscan API keys for verification
[etherscan]
ethereum_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
optimism_sepolia = { key = "${OPSCAN_API_KEY}", url = "https://api-sepolia-optimistic.etherscan.io/api" }
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }
avalanche_fuji = { key = "${SNOWTRACE_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }
